parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            PhpInvest:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Resources/mapping'
                prefix: 'PhpInvest\Entity'
                alias: 'PhpInvest'
