parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    PhpInvest\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    PhpInvest\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
